server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mymall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  redis:
    host: 47.98.137.54
    password: pan.2016
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.mall.item.pojo
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
mall:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: F:\\graduation-project\\rsa\\rsa.pub # 公钥地址
    cookieName: TOKEN # cookie的名称